POST http://localhost:3001/api/persons
Content-Type: application/json

{   "name": "Potato",
    "number": "08000-345534"
}

### Nameless

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    
    "number": "1242488802"
}

### Numberless
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Pekka"
    
}